name: MemoTrie
version: 0.6.10
synopsis: "Trie-based memo functions"
category: Data
description: >
  MemoTrie provides a basis for memoized functions over some domains,
  using tries.  It's based on ideas from Ralf Hinze and code from
  Spencer Janssen. Generic support thanks to Sam Boosalis.
  .
  Project wiki page: <http://haskell.org/haskellwiki/MemoTrie>
  .
  &#199; 2008-2019 by Conal Elliott; BSD3 license.

homepage: https://github.com/conal/MemoTrie
author: "Conal Elliot"
maintainer: "conal@conal.net"
github: "davidspies/MemoTrie"
copyright: "(c) 2008-2019 by Conal Elliott"
license: BSD3
license-file: COPYING
stability: experimental

extra-source-files:
  - README.md
  - changes.tw

dependencies:
  - base >= 4.7 && < 5
  - newtype-generics
  - void

library:
  source-dirs: src

tests:
  MemoTrie-example:
    main: Generic.hs
    source-dirs: examples
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - MemoTrie
